add SSH connectivity tests to deployment workflow for improved reliability

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -31,6 +31,33 @@ jobs:
             -t ${{ secrets.DOCKER_USERNAME }}/url-shortener-client:latest ./client
           docker push ${{ secrets.DOCKER_USERNAME }}/url-shortener-client:latest
 
+      # ===== TEST STEP START =====
+      - name: Test SSH connectivity
+        run: |
+          echo "Host: ${{ secrets.EC2_HOST }}"
+          
+          # Check if host accidentally contains a port
+          if [[ "${{ secrets.EC2_HOST }}" == *:* ]]; then
+            echo "Host contains port -> ${{ secrets.EC2_HOST }}"
+          fi
+
+          # Test port 22
+          timeout 5 bash -c ">/dev/tcp/${{ secrets.EC2_HOST }}/22" \
+            && echo "Port 22 reachable" \
+            || echo "Port 22 NOT reachable"
+
+          # Test SSH authentication
+          echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
+          chmod 600 key.pem
+          ssh -o StrictHostKeyChecking=no \
+              -o ConnectTimeout=5 \
+              -i key.pem \
+              -p 22 \
+              ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} \
+              "echo SSH success" || echo "SSH failed"
+      # ===== TEST STEP END =====
+
+
       # 2. Create the .env locally on the Runner
       - name: Create server .env file
         run: |
